### PR TITLE
Split out AS APIs to subclass

### LINKED ISSUE #79: Pinging the homeserver (or any other AS-API) fails if the bridge is configured with encryption enabled.
**Describe the bug**

The bridge loses it's ability to call AS-API endpoints because enabling encryption means the bot sets a device on the request, which means the requests end up failing.

>{"args":[{"body":{"errcode":"M_FORBIDDEN","error":"M_FORBIDDEN: This endpoint can only be called by appservices."},"errcode":"M_FORBIDDEN","error":"M_FORBIDDEN: This endpoint can only be called by appservices.","statusCode":403}],"error":"M_FORBIDDEN: M_FORBIDDEN: This endpoint can only be called by appservices.","level":"WARN","message":"Homeserver was pinged but was unable to validate the connection. You may be running a unsupported configuration.","module":"Bridge","timestamp":"00:27:14:893"}

We should fix this by holding onto a MatrixClient with permissions to access the bridge.

### PR DESCRIPTION
**Pull request by Half-Shot**
Fixes #79 

This splits out AS API requests to it's own self contained class, and ensures that the token overwrite performed when encryption is enabled does not affect our ability to make regular requests to the HS.

### CODE REVIEW

File: src/AppserviceApis.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+}
+
+/**
+ * APIs for use within the scope of an appservice.
+ */
+export class AppserviceApis {
+    /**
+     *
+     * @param client A client with the appservice token configured.
+     * @param appserviceId The `id` of the appservice, as per it's registration file.
```
Comment (AndrewFerr) [inline src/AppserviceApis.ts]:
```suggestion
     * @param appserviceId The `id` of the appservice, as per its registration file.
```

File: src/AppserviceApis.ts [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+     */
+    constructor(private readonly client: MatrixClient, private readonly appserviceId?: string) { }
```
Comment (AndrewFerr) [inline src/AppserviceApis.ts:16]: Instead of expecting the caller to set the proper access token on the client, how about doing it here?

```suggestion
    private client: MatrixClient;
    private appserviceId: string;

    constructor(homeserverUrl: string, registration: IAppserviceRegistration) {
        this.client = new MatrixClient(homeserverUrl, registration.as_token);
        this.appserviceId = registration.id;
    }
```

With that said, this recommendation is inconsistent with the other `*Apis` classes which accept a ready-made client in their constructors.

File: src/AppserviceApis.ts [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+
+    /**
+     * This API asks the homeserver to call the /_matrix/app/v1/ping endpoint on the application service
+     * to ensure that the homeserver can communicate with the application service.
+     * @param transactionId A unique ID that identifies the ping request.
+     */
+    public pingHomeserver(transactionId?: string): Promise<PingHomeserverResponse> {
```
Comment (AndrewFerr) [inline src/AppserviceApis.ts]: Although this endpoint accepts an undefined `transaction_id`, the SDK always sets it & expects one to be present in `/app/v1/ping` requests from the homeserver, so maybe it's worth making it mandatory here.

```suggestion
    public pingHomeserver(transactionId: string): Promise<PingHomeserverResponse> {
```

**Review by AndrewFerr — CHANGES_REQUESTED** [review]

File: src/AppserviceApis.ts (hunk 2 above)
Comment (Half-Shot) [reply src/AppserviceApis.ts:16]: Yeah I'm partial to following the other APIs here?

File: src/AppserviceApis.ts (hunk 3 above)
Comment (Half-Shot) [reply src/AppserviceApis.ts]: Yup, this makes sense to me.
